language: java
dist: bionic
jdk: openjdk11
env:
  global:
    - PYENV_VERSION=3.7
    - AWS_REGION="us-east-1"
    - AWS_DEFAULT_REGION=$AWS_REGION
install:
  - pip3 install --user pre-commit cloudformation-cli-java-plugin
script:
  - pre-commit run --all-files
  - cd "$TRAVIS_BUILD_DIR/costcategory"
  - mvn clean verify --no-transfer-progress
after_script:
  - cat "$TRAVIS_BUILD_DIR/costcategory/rpdk.log"
