AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::CE::CostCategory resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.ce.costcategory.HandlerWrapper::handleRequest
      Runtime: java21
      CodeUri: ./target/aws-ce-costcategory-handler-1.0-SNAPSHOT.jar
      MemorySize: 512

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.ce.costcategory.HandlerWrapper::testEntrypoint
      Runtime: java21
      CodeUri: ./target/aws-ce-costcategory-handler-1.0-SNAPSHOT.jar
      MemorySize: 512
